language: python
python:
  - 3.7
install:
  - pip install pipenv codecov
  - pipenv sync --dev
script:
  - pipenv run flake8
  - pipenv run pytest libpythonpro --cov=libpythonpro
after_success:
  - codecov