language: python
python:
  - 3.7
install:
  - pip install -q pipenv codecov
  - pipenv sync -d
script:
  - pipenv run flake8
  - pipenv run pytest libpythonpro --cov=libpythonpro
after_success:
  - codecov
