language: python
python:
  - 3.6
  - 3.7
install:
  # main
  - pip install -r requirements.txt
  # developer
  - pip install -r requirements-dev.txt
script:
  - flake8
  - pytest libpythonpro --cov=libpythonpro
  - codecov